### ISSUE TITLE
Understanding remediation actions

### ISSUE THREAD

**Issue by qgrosperrin** [hackthelegacy/hack400tool#3]
Hi ! Thanks for the tool. 
I was auditing a system and found out I could escalate privileges from a regular user to that of QSECOFR (using the dedicated tab in the tool). I was looking at the code and it calls the 'escalatePrivilegeWithoutPassword' with userName 'QSECOFR' and passwordType '*NOPWD'. That being said I was able to confirm this particular user profile is configured with a password so I'm not sure why this trick is possible ?

Are you able to shed some light on this please ? There is obviously a misconfiguration unless this is expected and I'm trying to fix this.
Thank you

**Comment by hackthelegacy** [comment]
Hi Quentin,

Thanks for reaching out and glad to see the tool was useful for you!

The “trick” behind the privilege escalation is possible with no password check only if you are authorized to the profile you’re escalating the rights with - in most of the cases it’s because the PUBLIC privileges of the user profile object (*USRPRF) is set to other value than *EXCLUDE. Other option could be that your current profile has the escalating user profile set as group profile, supplemental group or has in other way been authorized to the profile you’re escalating to. In that case the password is not checked - regardless of whether it’s set or not.

To mitigate this, the access to the profile objects should be limited and public access rights system value (QCRTAUT) should be set to *EXCLUDE.
You can use the tool to enumerate the user profiles you are allowed to escalate to which can help you in spotting the misconfigured access rights.

Good luck!

Thanks,
Bart

**Comment by qgrosperrin** [comment]
Sweet. Thanks a lot for the detailed explanation. 
Makes a lot more sense now :)

**Comment by qgrosperrin** [comment]
Ok, I checked the authority for QSECOFR user profile I'm escalating to and also the user I'm escalating from and both have PUBLIC authority with *EXCLUDE. 

The user profile I'm escalating from is part of a group (present in both Group Profile and Supplemental Group fields), but this group doesn't have additional rights to change the user profile object. On the other hand, that group is granted special authority for *ALLOBJ and *JOBCTL - could this be why I can escalate ?

From the doc it says the below, so assuming the above is correct:
Even if the user has *EXCLUDE authority to an object, *ALLOBJ special authority still allows the user to access the object.
Risks: *ALLOBJ special authority gives the user extensive authority over all resources on the system. The user can view, change, or delete any object. The user can also grant to other users the authority to use objects.

I understand *ALLOBJ is essentially free-reign. That being said, I'm trying to understand why when I was trying to run certain commands with my local user profile, such as 'ANZDFTPWD', I was getting errors saying I don't have *ALLOBJ authority. BUT if the user profile is part of a group with *ALLOBJ authority, I can escalate and do user profile swapping.

**Comment by qgrosperrin** [comment]
> I understand *ALLOBJ is essentially free-reign. That being said, I'm trying to understand why when I was trying to run certain commands with my local user profile, such as 'ANZDFTPWD', I was getting errors saying I don't have *ALLOBJ authority. BUT if the user profile is part of a group with *ALLOBJ authority, I can escalate and do user profile swapping.

The user profile doesn't have *ALLOBJ authority, but the group does.

**Comment by hackthelegacy** [comment]
The reason is that the effective access rights and special authorities of a user are a sum of all special authorities of its group profiles - so if the group/supplemental group has *ALLOBJ, the user will get it as well. This way you override any *EXCLUDE (unless a specific *EXCLUDE to an object is set to your own profile).

**Comment by qgrosperrin** [comment]
thanks!
